library("SummarizedExperiment")
library("tidyverse")
library("DEP")
library("RColorBrewer")
library("testthat")
library("shiny")
library("shinydashboard")
library("shinyjs")
library("shinyalert")
library("ComplexHeatmap")
library("limma")
library("DT")
library("ggrepel")
source("R/functions.R")
source("R/volcano_function.R")
source("R/tests.R")
source("R/demo_functions.R")

#enableBookmarking("server")


